import mxnet as mx
data = mx.symbol.Variable(name='data')
conv1_7x7_s2 = mx.symbol.Convolution(name='conv1_7x7_s2', data=data , num_filter=64, pad=(3, 3), kernel=(7,7), stride=(2,2), no_bias=True)
conv1_7x7_s2_bn = mx.symbol.BatchNorm(name='conv1_7x7_s2_bn', data=conv1_7x7_s2 , use_global_stats=True, fix_gamma=False, eps=0.000100)
conv1_7x7_s2_bn_scale = conv1_7x7_s2_bn
conv1_relu_7x7 = mx.symbol.Activation(name='conv1_relu_7x7', data=conv1_7x7_s2_bn_scale , act_type='relu')
pool1_3x3_s2 = mx.symbol.Pooling(name='pool1_3x3_s2', data=conv1_relu_7x7 , pooling_convention='full', pad=(0,0), kernel=(3,3), stride=(2,2), pool_type='max')
conv2_3x3_reduce = mx.symbol.Convolution(name='conv2_3x3_reduce', data=pool1_3x3_s2 , num_filter=64, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=True)
conv2_3x3_reduce_bn = mx.symbol.BatchNorm(name='conv2_3x3_reduce_bn', data=conv2_3x3_reduce , use_global_stats=True, fix_gamma=False, eps=0.000100)
conv2_3x3_reduce_bn_scale = conv2_3x3_reduce_bn
conv2_relu_3x3_reduce = mx.symbol.Activation(name='conv2_relu_3x3_reduce', data=conv2_3x3_reduce_bn_scale , act_type='relu')
conv2_3x3 = mx.symbol.Convolution(name='conv2_3x3', data=conv2_relu_3x3_reduce , num_filter=192, pad=(1, 1), kernel=(3,3), stride=(1,1), no_bias=True)
conv2_3x3_bn = mx.symbol.BatchNorm(name='conv2_3x3_bn', data=conv2_3x3 , use_global_stats=True, fix_gamma=False, eps=0.000100)
conv2_3x3_bn_scale = conv2_3x3_bn
conv2_relu_3x3 = mx.symbol.Activation(name='conv2_relu_3x3', data=conv2_3x3_bn_scale , act_type='relu')
pool2_3x3_s2 = mx.symbol.Pooling(name='pool2_3x3_s2', data=conv2_relu_3x3 , pooling_convention='full', pad=(0,0), kernel=(3,3), stride=(2,2), pool_type='max')
inception_3a_1x1 = mx.symbol.Convolution(name='inception_3a_1x1', data=pool2_3x3_s2 , num_filter=64, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=True)
inception_3a_1x1_bn = mx.symbol.BatchNorm(name='inception_3a_1x1_bn', data=inception_3a_1x1 , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_3a_1x1_bn_scale = inception_3a_1x1_bn
inception_3a_relu_1x1 = mx.symbol.Activation(name='inception_3a_relu_1x1', data=inception_3a_1x1_bn_scale , act_type='relu')
inception_3a_3x3_reduce = mx.symbol.Convolution(name='inception_3a_3x3_reduce', data=pool2_3x3_s2 , num_filter=64, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=True)
inception_3a_3x3_reduce_bn = mx.symbol.BatchNorm(name='inception_3a_3x3_reduce_bn', data=inception_3a_3x3_reduce , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_3a_3x3_reduce_bn_scale = inception_3a_3x3_reduce_bn
inception_3a_relu_3x3_reduce = mx.symbol.Activation(name='inception_3a_relu_3x3_reduce', data=inception_3a_3x3_reduce_bn_scale , act_type='relu')
inception_3a_3x3 = mx.symbol.Convolution(name='inception_3a_3x3', data=inception_3a_relu_3x3_reduce , num_filter=64, pad=(1, 1), kernel=(3,3), stride=(1,1), no_bias=True)
inception_3a_3x3_bn = mx.symbol.BatchNorm(name='inception_3a_3x3_bn', data=inception_3a_3x3 , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_3a_3x3_bn_scale = inception_3a_3x3_bn
inception_3a_relu_3x3 = mx.symbol.Activation(name='inception_3a_relu_3x3', data=inception_3a_3x3_bn_scale , act_type='relu')
inception_3a_double3x3_reduce = mx.symbol.Convolution(name='inception_3a_double3x3_reduce', data=pool2_3x3_s2 , num_filter=64, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=True)
inception_3a_double3x3_reduce_bn = mx.symbol.BatchNorm(name='inception_3a_double3x3_reduce_bn', data=inception_3a_double3x3_reduce , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_3a_double3x3_reduce_bn_scale = inception_3a_double3x3_reduce_bn
inception_3a_relu_double3x3_reduce = mx.symbol.Activation(name='inception_3a_relu_double3x3_reduce', data=inception_3a_double3x3_reduce_bn_scale , act_type='relu')
inception_3a_double3x3a = mx.symbol.Convolution(name='inception_3a_double3x3a', data=inception_3a_relu_double3x3_reduce , num_filter=96, pad=(1, 1), kernel=(3,3), stride=(1,1), no_bias=True)
inception_3a_double3x3a_bn = mx.symbol.BatchNorm(name='inception_3a_double3x3a_bn', data=inception_3a_double3x3a , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_3a_double3x3a_bn_scale = inception_3a_double3x3a_bn
inception_3a_relu_double3x3a = mx.symbol.Activation(name='inception_3a_relu_double3x3a', data=inception_3a_double3x3a_bn_scale , act_type='relu')
inception_3a_double3x3b = mx.symbol.Convolution(name='inception_3a_double3x3b', data=inception_3a_relu_double3x3a , num_filter=96, pad=(1, 1), kernel=(3,3), stride=(1,1), no_bias=True)
inception_3a_double3x3b_bn = mx.symbol.BatchNorm(name='inception_3a_double3x3b_bn', data=inception_3a_double3x3b , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_3a_double3x3b_bn_scale = inception_3a_double3x3b_bn
inception_3a_relu_double3x3b = mx.symbol.Activation(name='inception_3a_relu_double3x3b', data=inception_3a_double3x3b_bn_scale , act_type='relu')
inception_3a_pool = mx.symbol.Pooling(name='inception_3a_pool', data=pool2_3x3_s2 , pooling_convention='full', pad=(1,1), kernel=(3,3), stride=(1,1), pool_type='avg')
inception_3a_pool_proj = mx.symbol.Convolution(name='inception_3a_pool_proj', data=inception_3a_pool , num_filter=32, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=True)
inception_3a_pool_proj_bn = mx.symbol.BatchNorm(name='inception_3a_pool_proj_bn', data=inception_3a_pool_proj , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_3a_pool_proj_bn_scale = inception_3a_pool_proj_bn
inception_3a_relu_pool_proj = mx.symbol.Activation(name='inception_3a_relu_pool_proj', data=inception_3a_pool_proj_bn_scale , act_type='relu')
inception_3a_concat = mx.symbol.Concat(name='inception_3a_concat', *[inception_3a_relu_1x1,inception_3a_relu_3x3,inception_3a_relu_double3x3b,inception_3a_relu_pool_proj] )
inception_3a_global_pool = mx.symbol.Pooling(name='inception_3a_global_pool', data=inception_3a_concat , pooling_convention='full', global_pool=True, kernel=(1,1), pool_type='avg')
inception_3a_1x1_down = mx.symbol.Convolution(name='inception_3a_1x1_down', data=inception_3a_global_pool , num_filter=16, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=False)
inception_3a_1x1_down_relu = mx.symbol.Activation(name='inception_3a_1x1_down_relu', data=inception_3a_1x1_down , act_type='relu')
inception_3a_1x1_up = mx.symbol.Convolution(name='inception_3a_1x1_up', data=inception_3a_1x1_down_relu , num_filter=256, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=False)
inception_3a_prob = mx.symbol.Activation(name='inception_3a_prob', data=inception_3a_1x1_up , act_type='sigmoid')
inception_3a_prob_reshape = mx.symbol.Reshape(name='inception_3a_prob_reshape', data=inception_3a_prob , shape=(0,0, -2))
inception_3a_scale = mx.sym.broadcast_mul(inception_3a_concat, inception_3a_prob_reshape)
inception_3b_1x1 = mx.symbol.Convolution(name='inception_3b_1x1', data=inception_3a_scale , num_filter=64, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=True)
inception_3b_1x1_bn = mx.symbol.BatchNorm(name='inception_3b_1x1_bn', data=inception_3b_1x1 , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_3b_1x1_bn_scale = inception_3b_1x1_bn
inception_3b_relu_1x1 = mx.symbol.Activation(name='inception_3b_relu_1x1', data=inception_3b_1x1_bn_scale , act_type='relu')
inception_3b_3x3_reduce = mx.symbol.Convolution(name='inception_3b_3x3_reduce', data=inception_3a_scale , num_filter=64, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=True)
inception_3b_3x3_reduce_bn = mx.symbol.BatchNorm(name='inception_3b_3x3_reduce_bn', data=inception_3b_3x3_reduce , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_3b_3x3_reduce_bn_scale = inception_3b_3x3_reduce_bn
inception_3b_relu_3x3_reduce = mx.symbol.Activation(name='inception_3b_relu_3x3_reduce', data=inception_3b_3x3_reduce_bn_scale , act_type='relu')
inception_3b_3x3 = mx.symbol.Convolution(name='inception_3b_3x3', data=inception_3b_relu_3x3_reduce , num_filter=96, pad=(1, 1), kernel=(3,3), stride=(1,1), no_bias=True)
inception_3b_3x3_bn = mx.symbol.BatchNorm(name='inception_3b_3x3_bn', data=inception_3b_3x3 , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_3b_3x3_bn_scale = inception_3b_3x3_bn
inception_3b_relu_3x3 = mx.symbol.Activation(name='inception_3b_relu_3x3', data=inception_3b_3x3_bn_scale , act_type='relu')
inception_3b_double3x3_reduce = mx.symbol.Convolution(name='inception_3b_double3x3_reduce', data=inception_3a_scale , num_filter=64, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=True)
inception_3b_double3x3_reduce_bn = mx.symbol.BatchNorm(name='inception_3b_double3x3_reduce_bn', data=inception_3b_double3x3_reduce , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_3b_double3x3_reduce_bn_scale = inception_3b_double3x3_reduce_bn
inception_3b_relu_double3x3_reduce = mx.symbol.Activation(name='inception_3b_relu_double3x3_reduce', data=inception_3b_double3x3_reduce_bn_scale , act_type='relu')
inception_3b_double3x3a = mx.symbol.Convolution(name='inception_3b_double3x3a', data=inception_3b_relu_double3x3_reduce , num_filter=96, pad=(1, 1), kernel=(3,3), stride=(1,1), no_bias=True)
inception_3b_double3x3a_bn = mx.symbol.BatchNorm(name='inception_3b_double3x3a_bn', data=inception_3b_double3x3a , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_3b_double3x3a_bn_scale = inception_3b_double3x3a_bn
inception_3b_relu_double3x3a = mx.symbol.Activation(name='inception_3b_relu_double3x3a', data=inception_3b_double3x3a_bn_scale , act_type='relu')
inception_3b_double3x3b = mx.symbol.Convolution(name='inception_3b_double3x3b', data=inception_3b_relu_double3x3a , num_filter=96, pad=(1, 1), kernel=(3,3), stride=(1,1), no_bias=True)
inception_3b_double3x3b_bn = mx.symbol.BatchNorm(name='inception_3b_double3x3b_bn', data=inception_3b_double3x3b , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_3b_double3x3b_bn_scale = inception_3b_double3x3b_bn
inception_3b_relu_double3x3b = mx.symbol.Activation(name='inception_3b_relu_double3x3b', data=inception_3b_double3x3b_bn_scale , act_type='relu')
inception_3b_pool = mx.symbol.Pooling(name='inception_3b_pool', data=inception_3a_scale , pooling_convention='full', pad=(1,1), kernel=(3,3), stride=(1,1), pool_type='avg')
inception_3b_pool_proj = mx.symbol.Convolution(name='inception_3b_pool_proj', data=inception_3b_pool , num_filter=64, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=True)
inception_3b_pool_proj_bn = mx.symbol.BatchNorm(name='inception_3b_pool_proj_bn', data=inception_3b_pool_proj , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_3b_pool_proj_bn_scale = inception_3b_pool_proj_bn
inception_3b_relu_pool_proj = mx.symbol.Activation(name='inception_3b_relu_pool_proj', data=inception_3b_pool_proj_bn_scale , act_type='relu')
inception_3b_concat = mx.symbol.Concat(name='inception_3b_concat', *[inception_3b_relu_1x1,inception_3b_relu_3x3,inception_3b_relu_double3x3b,inception_3b_relu_pool_proj] )
inception_3b_global_pool = mx.symbol.Pooling(name='inception_3b_global_pool', data=inception_3b_concat , pooling_convention='full', global_pool=True, kernel=(1,1), pool_type='avg')
inception_3b_1x1_down = mx.symbol.Convolution(name='inception_3b_1x1_down', data=inception_3b_global_pool , num_filter=20, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=False)
inception_3b_1x1_down_relu = mx.symbol.Activation(name='inception_3b_1x1_down_relu', data=inception_3b_1x1_down , act_type='relu')
inception_3b_1x1_up = mx.symbol.Convolution(name='inception_3b_1x1_up', data=inception_3b_1x1_down_relu , num_filter=320, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=False)
inception_3b_prob = mx.symbol.Activation(name='inception_3b_prob', data=inception_3b_1x1_up , act_type='sigmoid')
inception_3b_prob_reshape = mx.symbol.Reshape(name='inception_3b_prob_reshape', data=inception_3b_prob , shape=(0,0, -2))
inception_3b_scale = mx.sym.broadcast_mul(inception_3b_concat, inception_3b_prob_reshape)
inception_3c_3x3_reduce = mx.symbol.Convolution(name='inception_3c_3x3_reduce', data=inception_3b_scale , num_filter=128, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=True)
inception_3c_3x3_reduce_bn = mx.symbol.BatchNorm(name='inception_3c_3x3_reduce_bn', data=inception_3c_3x3_reduce , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_3c_3x3_reduce_bn_scale = inception_3c_3x3_reduce_bn
inception_3c_relu_3x3_reduce = mx.symbol.Activation(name='inception_3c_relu_3x3_reduce', data=inception_3c_3x3_reduce_bn_scale , act_type='relu')
inception_3c_3x3 = mx.symbol.Convolution(name='inception_3c_3x3', data=inception_3c_relu_3x3_reduce , num_filter=160, pad=(1, 1), kernel=(3,3), stride=(2,2), no_bias=True)
inception_3c_3x3_bn = mx.symbol.BatchNorm(name='inception_3c_3x3_bn', data=inception_3c_3x3 , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_3c_3x3_bn_scale = inception_3c_3x3_bn
inception_3c_relu_3x3 = mx.symbol.Activation(name='inception_3c_relu_3x3', data=inception_3c_3x3_bn_scale , act_type='relu')
inception_3c_double3x3_reduce = mx.symbol.Convolution(name='inception_3c_double3x3_reduce', data=inception_3b_scale , num_filter=64, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=True)
inception_3c_double3x3_reduce_bn = mx.symbol.BatchNorm(name='inception_3c_double3x3_reduce_bn', data=inception_3c_double3x3_reduce , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_3c_double3x3_reduce_bn_scale = inception_3c_double3x3_reduce_bn
inception_3c_relu_double3x3_reduce = mx.symbol.Activation(name='inception_3c_relu_double3x3_reduce', data=inception_3c_double3x3_reduce_bn_scale , act_type='relu')
inception_3c_double3x3a = mx.symbol.Convolution(name='inception_3c_double3x3a', data=inception_3c_relu_double3x3_reduce , num_filter=96, pad=(1, 1), kernel=(3,3), stride=(1,1), no_bias=True)
inception_3c_double3x3a_bn = mx.symbol.BatchNorm(name='inception_3c_double3x3a_bn', data=inception_3c_double3x3a , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_3c_double3x3a_bn_scale = inception_3c_double3x3a_bn
inception_3c_relu_double3x3a = mx.symbol.Activation(name='inception_3c_relu_double3x3a', data=inception_3c_double3x3a_bn_scale , act_type='relu')
inception_3c_double3x3b = mx.symbol.Convolution(name='inception_3c_double3x3b', data=inception_3c_relu_double3x3a , num_filter=96, pad=(1, 1), kernel=(3,3), stride=(2,2), no_bias=True)
inception_3c_double3x3b_bn = mx.symbol.BatchNorm(name='inception_3c_double3x3b_bn', data=inception_3c_double3x3b , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_3c_double3x3b_bn_scale = inception_3c_double3x3b_bn
inception_3c_relu_double3x3b = mx.symbol.Activation(name='inception_3c_relu_double3x3b', data=inception_3c_double3x3b_bn_scale , act_type='relu')
inception_3c_pool_3x3_s2 = mx.symbol.Pooling(name='inception_3c_pool_3x3_s2', data=inception_3b_scale , pooling_convention='full', pad=(0,0), kernel=(3,3), stride=(2,2), pool_type='max')
inception_3c_concat = mx.symbol.Concat(name='inception_3c_concat', *[inception_3c_relu_3x3,inception_3c_relu_double3x3b,inception_3c_pool_3x3_s2] )
inception_3c_global_pool = mx.symbol.Pooling(name='inception_3c_global_pool', data=inception_3c_concat , pooling_convention='full', global_pool=True, kernel=(1,1), pool_type='avg')
inception_3c_1x1_down = mx.symbol.Convolution(name='inception_3c_1x1_down', data=inception_3c_global_pool , num_filter=36, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=False)
inception_3c_1x1_down_relu = mx.symbol.Activation(name='inception_3c_1x1_down_relu', data=inception_3c_1x1_down , act_type='relu')
inception_3c_1x1_up = mx.symbol.Convolution(name='inception_3c_1x1_up', data=inception_3c_1x1_down_relu , num_filter=576, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=False)
inception_3c_prob = mx.symbol.Activation(name='inception_3c_prob', data=inception_3c_1x1_up , act_type='sigmoid')
inception_3c_prob_reshape = mx.symbol.Reshape(name='inception_3c_prob_reshape', data=inception_3c_prob , shape=(0,0, -2))
inception_3c_scale = mx.sym.broadcast_mul(inception_3c_concat, inception_3c_prob_reshape)
inception_4a_1x1 = mx.symbol.Convolution(name='inception_4a_1x1', data=inception_3c_scale , num_filter=224, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=True)
inception_4a_1x1_bn = mx.symbol.BatchNorm(name='inception_4a_1x1_bn', data=inception_4a_1x1 , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_4a_1x1_bn_scale = inception_4a_1x1_bn
inception_4a_relu_1x1 = mx.symbol.Activation(name='inception_4a_relu_1x1', data=inception_4a_1x1_bn_scale , act_type='relu')
inception_4a_3x3_reduce = mx.symbol.Convolution(name='inception_4a_3x3_reduce', data=inception_3c_scale , num_filter=64, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=True)
inception_4a_3x3_reduce_bn = mx.symbol.BatchNorm(name='inception_4a_3x3_reduce_bn', data=inception_4a_3x3_reduce , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_4a_3x3_reduce_bn_scale = inception_4a_3x3_reduce_bn
inception_4a_relu_3x3_reduce = mx.symbol.Activation(name='inception_4a_relu_3x3_reduce', data=inception_4a_3x3_reduce_bn_scale , act_type='relu')
inception_4a_3x3 = mx.symbol.Convolution(name='inception_4a_3x3', data=inception_4a_relu_3x3_reduce , num_filter=96, pad=(1, 1), kernel=(3,3), stride=(1,1), no_bias=True)
inception_4a_3x3_bn = mx.symbol.BatchNorm(name='inception_4a_3x3_bn', data=inception_4a_3x3 , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_4a_3x3_bn_scale = inception_4a_3x3_bn
inception_4a_relu_3x3 = mx.symbol.Activation(name='inception_4a_relu_3x3', data=inception_4a_3x3_bn_scale , act_type='relu')
inception_4a_double3x3_reduce = mx.symbol.Convolution(name='inception_4a_double3x3_reduce', data=inception_3c_scale , num_filter=96, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=True)
inception_4a_double3x3_reduce_bn = mx.symbol.BatchNorm(name='inception_4a_double3x3_reduce_bn', data=inception_4a_double3x3_reduce , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_4a_double3x3_reduce_bn_scale = inception_4a_double3x3_reduce_bn
inception_4a_relu_double3x3_reduce = mx.symbol.Activation(name='inception_4a_relu_double3x3_reduce', data=inception_4a_double3x3_reduce_bn_scale , act_type='relu')
inception_4a_double3x3a = mx.symbol.Convolution(name='inception_4a_double3x3a', data=inception_4a_relu_double3x3_reduce , num_filter=128, pad=(1, 1), kernel=(3,3), stride=(1,1), no_bias=True)
inception_4a_double3x3a_bn = mx.symbol.BatchNorm(name='inception_4a_double3x3a_bn', data=inception_4a_double3x3a , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_4a_double3x3a_bn_scale = inception_4a_double3x3a_bn
inception_4a_relu_double3x3a = mx.symbol.Activation(name='inception_4a_relu_double3x3a', data=inception_4a_double3x3a_bn_scale , act_type='relu')
inception_4a_double3x3b = mx.symbol.Convolution(name='inception_4a_double3x3b', data=inception_4a_relu_double3x3a , num_filter=128, pad=(1, 1), kernel=(3,3), stride=(1,1), no_bias=True)
inception_4a_double3x3b_bn = mx.symbol.BatchNorm(name='inception_4a_double3x3b_bn', data=inception_4a_double3x3b , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_4a_double3x3b_bn_scale = inception_4a_double3x3b_bn
inception_4a_relu_double3x3b = mx.symbol.Activation(name='inception_4a_relu_double3x3b', data=inception_4a_double3x3b_bn_scale , act_type='relu')
inception_4a_pool = mx.symbol.Pooling(name='inception_4a_pool', data=inception_3c_scale , pooling_convention='full', pad=(1,1), kernel=(3,3), stride=(1,1), pool_type='avg')
inception_4a_pool_proj = mx.symbol.Convolution(name='inception_4a_pool_proj', data=inception_4a_pool , num_filter=128, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=True)
inception_4a_pool_proj_bn = mx.symbol.BatchNorm(name='inception_4a_pool_proj_bn', data=inception_4a_pool_proj , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_4a_pool_proj_bn_scale = inception_4a_pool_proj_bn
inception_4a_relu_pool_proj = mx.symbol.Activation(name='inception_4a_relu_pool_proj', data=inception_4a_pool_proj_bn_scale , act_type='relu')
inception_4a_concat = mx.symbol.Concat(name='inception_4a_concat', *[inception_4a_relu_1x1,inception_4a_relu_3x3,inception_4a_relu_double3x3b,inception_4a_relu_pool_proj] )
inception_4a_global_pool = mx.symbol.Pooling(name='inception_4a_global_pool', data=inception_4a_concat , pooling_convention='full', global_pool=True, kernel=(1,1), pool_type='avg')
inception_4a_1x1_down = mx.symbol.Convolution(name='inception_4a_1x1_down', data=inception_4a_global_pool , num_filter=36, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=False)
inception_4a_1x1_down_relu = mx.symbol.Activation(name='inception_4a_1x1_down_relu', data=inception_4a_1x1_down , act_type='relu')
inception_4a_1x1_up = mx.symbol.Convolution(name='inception_4a_1x1_up', data=inception_4a_1x1_down_relu , num_filter=576, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=False)
inception_4a_prob = mx.symbol.Activation(name='inception_4a_prob', data=inception_4a_1x1_up , act_type='sigmoid')
inception_4a_prob_reshape = mx.symbol.Reshape(name='inception_4a_prob_reshape', data=inception_4a_prob , shape=(0,0, -2))
inception_4a_scale = mx.sym.broadcast_mul(inception_4a_concat, inception_4a_prob_reshape)
inception_4b_1x1 = mx.symbol.Convolution(name='inception_4b_1x1', data=inception_4a_scale , num_filter=192, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=True)
inception_4b_1x1_bn = mx.symbol.BatchNorm(name='inception_4b_1x1_bn', data=inception_4b_1x1 , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_4b_1x1_bn_scale = inception_4b_1x1_bn
inception_4b_relu_1x1 = mx.symbol.Activation(name='inception_4b_relu_1x1', data=inception_4b_1x1_bn_scale , act_type='relu')
inception_4b_3x3_reduce = mx.symbol.Convolution(name='inception_4b_3x3_reduce', data=inception_4a_scale , num_filter=96, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=True)
inception_4b_3x3_reduce_bn = mx.symbol.BatchNorm(name='inception_4b_3x3_reduce_bn', data=inception_4b_3x3_reduce , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_4b_3x3_reduce_bn_scale = inception_4b_3x3_reduce_bn
inception_4b_relu_3x3_reduce = mx.symbol.Activation(name='inception_4b_relu_3x3_reduce', data=inception_4b_3x3_reduce_bn_scale , act_type='relu')
inception_4b_3x3 = mx.symbol.Convolution(name='inception_4b_3x3', data=inception_4b_relu_3x3_reduce , num_filter=128, pad=(1, 1), kernel=(3,3), stride=(1,1), no_bias=True)
inception_4b_3x3_bn = mx.symbol.BatchNorm(name='inception_4b_3x3_bn', data=inception_4b_3x3 , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_4b_3x3_bn_scale = inception_4b_3x3_bn
inception_4b_relu_3x3 = mx.symbol.Activation(name='inception_4b_relu_3x3', data=inception_4b_3x3_bn_scale , act_type='relu')
inception_4b_double3x3_reduce = mx.symbol.Convolution(name='inception_4b_double3x3_reduce', data=inception_4a_scale , num_filter=96, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=True)
inception_4b_double3x3_reduce_bn = mx.symbol.BatchNorm(name='inception_4b_double3x3_reduce_bn', data=inception_4b_double3x3_reduce , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_4b_double3x3_reduce_bn_scale = inception_4b_double3x3_reduce_bn
inception_4b_relu_double3x3_reduce = mx.symbol.Activation(name='inception_4b_relu_double3x3_reduce', data=inception_4b_double3x3_reduce_bn_scale , act_type='relu')
inception_4b_double3x3a = mx.symbol.Convolution(name='inception_4b_double3x3a', data=inception_4b_relu_double3x3_reduce , num_filter=128, pad=(1, 1), kernel=(3,3), stride=(1,1), no_bias=True)
inception_4b_double3x3a_bn = mx.symbol.BatchNorm(name='inception_4b_double3x3a_bn', data=inception_4b_double3x3a , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_4b_double3x3a_bn_scale = inception_4b_double3x3a_bn
inception_4b_relu_double3x3a = mx.symbol.Activation(name='inception_4b_relu_double3x3a', data=inception_4b_double3x3a_bn_scale , act_type='relu')
inception_4b_double3x3b = mx.symbol.Convolution(name='inception_4b_double3x3b', data=inception_4b_relu_double3x3a , num_filter=128, pad=(1, 1), kernel=(3,3), stride=(1,1), no_bias=True)
inception_4b_double3x3b_bn = mx.symbol.BatchNorm(name='inception_4b_double3x3b_bn', data=inception_4b_double3x3b , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_4b_double3x3b_bn_scale = inception_4b_double3x3b_bn
inception_4b_relu_double3x3b = mx.symbol.Activation(name='inception_4b_relu_double3x3b', data=inception_4b_double3x3b_bn_scale , act_type='relu')
inception_4b_pool = mx.symbol.Pooling(name='inception_4b_pool', data=inception_4a_scale , pooling_convention='full', pad=(1,1), kernel=(3,3), stride=(1,1), pool_type='avg')
inception_4b_pool_proj = mx.symbol.Convolution(name='inception_4b_pool_proj', data=inception_4b_pool , num_filter=128, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=True)
inception_4b_pool_proj_bn = mx.symbol.BatchNorm(name='inception_4b_pool_proj_bn', data=inception_4b_pool_proj , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_4b_pool_proj_bn_scale = inception_4b_pool_proj_bn
inception_4b_relu_pool_proj = mx.symbol.Activation(name='inception_4b_relu_pool_proj', data=inception_4b_pool_proj_bn_scale , act_type='relu')
inception_4b_concat = mx.symbol.Concat(name='inception_4b_concat', *[inception_4b_relu_1x1,inception_4b_relu_3x3,inception_4b_relu_double3x3b,inception_4b_relu_pool_proj] )
inception_4b_global_pool = mx.symbol.Pooling(name='inception_4b_global_pool', data=inception_4b_concat , pooling_convention='full', global_pool=True, kernel=(1,1), pool_type='avg')
inception_4b_1x1_down = mx.symbol.Convolution(name='inception_4b_1x1_down', data=inception_4b_global_pool , num_filter=36, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=False)
inception_4b_1x1_down_relu = mx.symbol.Activation(name='inception_4b_1x1_down_relu', data=inception_4b_1x1_down , act_type='relu')
inception_4b_1x1_up = mx.symbol.Convolution(name='inception_4b_1x1_up', data=inception_4b_1x1_down_relu , num_filter=576, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=False)
inception_4b_prob = mx.symbol.Activation(name='inception_4b_prob', data=inception_4b_1x1_up , act_type='sigmoid')
inception_4b_prob_reshape = mx.symbol.Reshape(name='inception_4b_prob_reshape', data=inception_4b_prob , shape=(0,0, -2))
inception_4b_scale = mx.sym.broadcast_mul(inception_4b_concat, inception_4b_prob_reshape)
inception_4c_1x1 = mx.symbol.Convolution(name='inception_4c_1x1', data=inception_4b_scale , num_filter=160, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=True)
inception_4c_1x1_bn = mx.symbol.BatchNorm(name='inception_4c_1x1_bn', data=inception_4c_1x1 , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_4c_1x1_bn_scale = inception_4c_1x1_bn
inception_4c_relu_1x1 = mx.symbol.Activation(name='inception_4c_relu_1x1', data=inception_4c_1x1_bn_scale , act_type='relu')
inception_4c_3x3_reduce = mx.symbol.Convolution(name='inception_4c_3x3_reduce', data=inception_4b_scale , num_filter=128, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=True)
inception_4c_3x3_reduce_bn = mx.symbol.BatchNorm(name='inception_4c_3x3_reduce_bn', data=inception_4c_3x3_reduce , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_4c_3x3_reduce_bn_scale = inception_4c_3x3_reduce_bn
inception_4c_relu_3x3_reduce = mx.symbol.Activation(name='inception_4c_relu_3x3_reduce', data=inception_4c_3x3_reduce_bn_scale , act_type='relu')
inception_4c_3x3 = mx.symbol.Convolution(name='inception_4c_3x3', data=inception_4c_relu_3x3_reduce , num_filter=160, pad=(1, 1), kernel=(3,3), stride=(1,1), no_bias=True)
inception_4c_3x3_bn = mx.symbol.BatchNorm(name='inception_4c_3x3_bn', data=inception_4c_3x3 , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_4c_3x3_bn_scale = inception_4c_3x3_bn
inception_4c_relu_3x3 = mx.symbol.Activation(name='inception_4c_relu_3x3', data=inception_4c_3x3_bn_scale , act_type='relu')
inception_4c_double3x3_reduce = mx.symbol.Convolution(name='inception_4c_double3x3_reduce', data=inception_4b_scale , num_filter=128, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=True)
inception_4c_double3x3_reduce_bn = mx.symbol.BatchNorm(name='inception_4c_double3x3_reduce_bn', data=inception_4c_double3x3_reduce , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_4c_double3x3_reduce_bn_scale = inception_4c_double3x3_reduce_bn
inception_4c_relu_double3x3_reduce = mx.symbol.Activation(name='inception_4c_relu_double3x3_reduce', data=inception_4c_double3x3_reduce_bn_scale , act_type='relu')
inception_4c_double3x3a = mx.symbol.Convolution(name='inception_4c_double3x3a', data=inception_4c_relu_double3x3_reduce , num_filter=160, pad=(1, 1), kernel=(3,3), stride=(1,1), no_bias=True)
inception_4c_double3x3a_bn = mx.symbol.BatchNorm(name='inception_4c_double3x3a_bn', data=inception_4c_double3x3a , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_4c_double3x3a_bn_scale = inception_4c_double3x3a_bn
inception_4c_relu_double3x3a = mx.symbol.Activation(name='inception_4c_relu_double3x3a', data=inception_4c_double3x3a_bn_scale , act_type='relu')
inception_4c_double3x3b = mx.symbol.Convolution(name='inception_4c_double3x3b', data=inception_4c_relu_double3x3a , num_filter=160, pad=(1, 1), kernel=(3,3), stride=(1,1), no_bias=True)
inception_4c_double3x3b_bn = mx.symbol.BatchNorm(name='inception_4c_double3x3b_bn', data=inception_4c_double3x3b , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_4c_double3x3b_bn_scale = inception_4c_double3x3b_bn
inception_4c_relu_double3x3b = mx.symbol.Activation(name='inception_4c_relu_double3x3b', data=inception_4c_double3x3b_bn_scale , act_type='relu')
inception_4c_pool = mx.symbol.Pooling(name='inception_4c_pool', data=inception_4b_scale , pooling_convention='full', pad=(1,1), kernel=(3,3), stride=(1,1), pool_type='avg')
inception_4c_pool_proj = mx.symbol.Convolution(name='inception_4c_pool_proj', data=inception_4c_pool , num_filter=128, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=True)
inception_4c_pool_proj_bn = mx.symbol.BatchNorm(name='inception_4c_pool_proj_bn', data=inception_4c_pool_proj , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_4c_pool_proj_bn_scale = inception_4c_pool_proj_bn
inception_4c_relu_pool_proj = mx.symbol.Activation(name='inception_4c_relu_pool_proj', data=inception_4c_pool_proj_bn_scale , act_type='relu')
inception_4c_concat = mx.symbol.Concat(name='inception_4c_concat', *[inception_4c_relu_1x1,inception_4c_relu_3x3,inception_4c_relu_double3x3b,inception_4c_relu_pool_proj] )
inception_4c_global_pool = mx.symbol.Pooling(name='inception_4c_global_pool', data=inception_4c_concat , pooling_convention='full', global_pool=True, kernel=(1,1), pool_type='avg')
inception_4c_1x1_down = mx.symbol.Convolution(name='inception_4c_1x1_down', data=inception_4c_global_pool , num_filter=38, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=False)
inception_4c_1x1_down_relu = mx.symbol.Activation(name='inception_4c_1x1_down_relu', data=inception_4c_1x1_down , act_type='relu')
inception_4c_1x1_up = mx.symbol.Convolution(name='inception_4c_1x1_up', data=inception_4c_1x1_down_relu , num_filter=608, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=False)
inception_4c_prob = mx.symbol.Activation(name='inception_4c_prob', data=inception_4c_1x1_up , act_type='sigmoid')
inception_4c_prob_reshape = mx.symbol.Reshape(name='inception_4c_prob_reshape', data=inception_4c_prob , shape=(0,0, -2))
inception_4c_scale = mx.sym.broadcast_mul(inception_4c_concat, inception_4c_prob_reshape)
inception_4d_1x1 = mx.symbol.Convolution(name='inception_4d_1x1', data=inception_4c_scale , num_filter=96, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=True)
inception_4d_1x1_bn = mx.symbol.BatchNorm(name='inception_4d_1x1_bn', data=inception_4d_1x1 , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_4d_1x1_bn_scale = inception_4d_1x1_bn
inception_4d_relu_1x1 = mx.symbol.Activation(name='inception_4d_relu_1x1', data=inception_4d_1x1_bn_scale , act_type='relu')
inception_4d_3x3_reduce = mx.symbol.Convolution(name='inception_4d_3x3_reduce', data=inception_4c_scale , num_filter=128, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=True)
inception_4d_3x3_reduce_bn = mx.symbol.BatchNorm(name='inception_4d_3x3_reduce_bn', data=inception_4d_3x3_reduce , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_4d_3x3_reduce_bn_scale = inception_4d_3x3_reduce_bn
inception_4d_relu_3x3_reduce = mx.symbol.Activation(name='inception_4d_relu_3x3_reduce', data=inception_4d_3x3_reduce_bn_scale , act_type='relu')
inception_4d_3x3 = mx.symbol.Convolution(name='inception_4d_3x3', data=inception_4d_relu_3x3_reduce , num_filter=192, pad=(1, 1), kernel=(3,3), stride=(1,1), no_bias=True)
inception_4d_3x3_bn = mx.symbol.BatchNorm(name='inception_4d_3x3_bn', data=inception_4d_3x3 , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_4d_3x3_bn_scale = inception_4d_3x3_bn
inception_4d_relu_3x3 = mx.symbol.Activation(name='inception_4d_relu_3x3', data=inception_4d_3x3_bn_scale , act_type='relu')
inception_4d_double3x3_reduce = mx.symbol.Convolution(name='inception_4d_double3x3_reduce', data=inception_4c_scale , num_filter=160, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=True)
inception_4d_double3x3_reduce_bn = mx.symbol.BatchNorm(name='inception_4d_double3x3_reduce_bn', data=inception_4d_double3x3_reduce , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_4d_double3x3_reduce_bn_scale = inception_4d_double3x3_reduce_bn
inception_4d_relu_double3x3_reduce = mx.symbol.Activation(name='inception_4d_relu_double3x3_reduce', data=inception_4d_double3x3_reduce_bn_scale , act_type='relu')
inception_4d_double3x3a = mx.symbol.Convolution(name='inception_4d_double3x3a', data=inception_4d_relu_double3x3_reduce , num_filter=192, pad=(1, 1), kernel=(3,3), stride=(1,1), no_bias=True)
inception_4d_double3x3a_bn = mx.symbol.BatchNorm(name='inception_4d_double3x3a_bn', data=inception_4d_double3x3a , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_4d_double3x3a_bn_scale = inception_4d_double3x3a_bn
inception_4d_relu_double3x3a = mx.symbol.Activation(name='inception_4d_relu_double3x3a', data=inception_4d_double3x3a_bn_scale , act_type='relu')
inception_4d_double3x3b = mx.symbol.Convolution(name='inception_4d_double3x3b', data=inception_4d_relu_double3x3a , num_filter=192, pad=(1, 1), kernel=(3,3), stride=(1,1), no_bias=True)
inception_4d_double3x3b_bn = mx.symbol.BatchNorm(name='inception_4d_double3x3b_bn', data=inception_4d_double3x3b , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_4d_double3x3b_bn_scale = inception_4d_double3x3b_bn
inception_4d_relu_double3x3b = mx.symbol.Activation(name='inception_4d_relu_double3x3b', data=inception_4d_double3x3b_bn_scale , act_type='relu')
inception_4d_pool = mx.symbol.Pooling(name='inception_4d_pool', data=inception_4c_scale , pooling_convention='full', pad=(1,1), kernel=(3,3), stride=(1,1), pool_type='avg')
inception_4d_pool_proj = mx.symbol.Convolution(name='inception_4d_pool_proj', data=inception_4d_pool , num_filter=128, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=True)
inception_4d_pool_proj_bn = mx.symbol.BatchNorm(name='inception_4d_pool_proj_bn', data=inception_4d_pool_proj , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_4d_pool_proj_bn_scale = inception_4d_pool_proj_bn
inception_4d_relu_pool_proj = mx.symbol.Activation(name='inception_4d_relu_pool_proj', data=inception_4d_pool_proj_bn_scale , act_type='relu')
inception_4d_concat = mx.symbol.Concat(name='inception_4d_concat', *[inception_4d_relu_1x1,inception_4d_relu_3x3,inception_4d_relu_double3x3b,inception_4d_relu_pool_proj] )
inception_4d_global_pool = mx.symbol.Pooling(name='inception_4d_global_pool', data=inception_4d_concat , pooling_convention='full', global_pool=True, kernel=(1,1), pool_type='avg')
inception_4d_1x1_down = mx.symbol.Convolution(name='inception_4d_1x1_down', data=inception_4d_global_pool , num_filter=38, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=False)
inception_4d_1x1_down_relu = mx.symbol.Activation(name='inception_4d_1x1_down_relu', data=inception_4d_1x1_down , act_type='relu')
inception_4d_1x1_up = mx.symbol.Convolution(name='inception_4d_1x1_up', data=inception_4d_1x1_down_relu , num_filter=608, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=False)
inception_4d_prob = mx.symbol.Activation(name='inception_4d_prob', data=inception_4d_1x1_up , act_type='sigmoid')
inception_4d_prob_reshape = mx.symbol.Reshape(name='inception_4d_prob_reshape', data=inception_4d_prob , shape=(0,0, -2))
inception_4d_scale = mx.sym.broadcast_mul(inception_4d_concat, inception_4d_prob_reshape)
inception_4e_3x3_reduce = mx.symbol.Convolution(name='inception_4e_3x3_reduce', data=inception_4d_scale , num_filter=128, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=True)
inception_4e_3x3_reduce_bn = mx.symbol.BatchNorm(name='inception_4e_3x3_reduce_bn', data=inception_4e_3x3_reduce , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_4e_3x3_reduce_bn_scale = inception_4e_3x3_reduce_bn
inception_4e_relu_3x3_reduce = mx.symbol.Activation(name='inception_4e_relu_3x3_reduce', data=inception_4e_3x3_reduce_bn_scale , act_type='relu')
inception_4e_3x3 = mx.symbol.Convolution(name='inception_4e_3x3', data=inception_4e_relu_3x3_reduce , num_filter=192, pad=(1, 1), kernel=(3,3), stride=(2,2), no_bias=True)
inception_4e_3x3_bn = mx.symbol.BatchNorm(name='inception_4e_3x3_bn', data=inception_4e_3x3 , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_4e_3x3_bn_scale = inception_4e_3x3_bn
inception_4e_relu_3x3 = mx.symbol.Activation(name='inception_4e_relu_3x3', data=inception_4e_3x3_bn_scale , act_type='relu')
inception_4e_double3x3_reduce = mx.symbol.Convolution(name='inception_4e_double3x3_reduce', data=inception_4d_scale , num_filter=192, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=True)
inception_4e_double3x3_reduce_bn = mx.symbol.BatchNorm(name='inception_4e_double3x3_reduce_bn', data=inception_4e_double3x3_reduce , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_4e_double3x3_reduce_bn_scale = inception_4e_double3x3_reduce_bn
inception_4e_relu_double3x3_reduce = mx.symbol.Activation(name='inception_4e_relu_double3x3_reduce', data=inception_4e_double3x3_reduce_bn_scale , act_type='relu')
inception_4e_double3x3a = mx.symbol.Convolution(name='inception_4e_double3x3a', data=inception_4e_relu_double3x3_reduce , num_filter=256, pad=(1, 1), kernel=(3,3), stride=(1,1), no_bias=True)
inception_4e_double3x3a_bn = mx.symbol.BatchNorm(name='inception_4e_double3x3a_bn', data=inception_4e_double3x3a , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_4e_double3x3a_bn_scale = inception_4e_double3x3a_bn
inception_4e_relu_double3x3a = mx.symbol.Activation(name='inception_4e_relu_double3x3a', data=inception_4e_double3x3a_bn_scale , act_type='relu')
inception_4e_double3x3b = mx.symbol.Convolution(name='inception_4e_double3x3b', data=inception_4e_relu_double3x3a , num_filter=256, pad=(1, 1), kernel=(3,3), stride=(2,2), no_bias=True)
inception_4e_double3x3b_bn = mx.symbol.BatchNorm(name='inception_4e_double3x3b_bn', data=inception_4e_double3x3b , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_4e_double3x3b_bn_scale = inception_4e_double3x3b_bn
inception_4e_relu_double3x3b = mx.symbol.Activation(name='inception_4e_relu_double3x3b', data=inception_4e_double3x3b_bn_scale , act_type='relu')
inception_4e_pool_3x3_s2 = mx.symbol.Pooling(name='inception_4e_pool_3x3_s2', data=inception_4d_scale , pooling_convention='full', pad=(0,0), kernel=(3,3), stride=(2,2), pool_type='max')
inception_4e_concat = mx.symbol.Concat(name='inception_4e_concat', *[inception_4e_relu_3x3,inception_4e_relu_double3x3b,inception_4e_pool_3x3_s2] )
inception_4e_global_pool = mx.symbol.Pooling(name='inception_4e_global_pool', data=inception_4e_concat , pooling_convention='full', global_pool=True, kernel=(1,1), pool_type='avg')
inception_4e_1x1_down = mx.symbol.Convolution(name='inception_4e_1x1_down', data=inception_4e_global_pool , num_filter=66, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=False)
inception_4e_1x1_down_relu = mx.symbol.Activation(name='inception_4e_1x1_down_relu', data=inception_4e_1x1_down , act_type='relu')
inception_4e_1x1_up = mx.symbol.Convolution(name='inception_4e_1x1_up', data=inception_4e_1x1_down_relu , num_filter=1056, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=False)
inception_4e_prob = mx.symbol.Activation(name='inception_4e_prob', data=inception_4e_1x1_up , act_type='sigmoid')
inception_4e_prob_reshape = mx.symbol.Reshape(name='inception_4e_prob_reshape', data=inception_4e_prob , shape=(0,0, -2))
inception_4e_scale = mx.sym.broadcast_mul(inception_4e_concat, inception_4e_prob_reshape)
inception_5a_1x1 = mx.symbol.Convolution(name='inception_5a_1x1', data=inception_4e_scale , num_filter=352, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=True)
inception_5a_1x1_bn = mx.symbol.BatchNorm(name='inception_5a_1x1_bn', data=inception_5a_1x1 , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_5a_1x1_bn_scale = inception_5a_1x1_bn
inception_5a_relu_1x1 = mx.symbol.Activation(name='inception_5a_relu_1x1', data=inception_5a_1x1_bn_scale , act_type='relu')
inception_5a_3x3_reduce = mx.symbol.Convolution(name='inception_5a_3x3_reduce', data=inception_4e_scale , num_filter=192, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=True)
inception_5a_3x3_reduce_bn = mx.symbol.BatchNorm(name='inception_5a_3x3_reduce_bn', data=inception_5a_3x3_reduce , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_5a_3x3_reduce_bn_scale = inception_5a_3x3_reduce_bn
inception_5a_relu_3x3_reduce = mx.symbol.Activation(name='inception_5a_relu_3x3_reduce', data=inception_5a_3x3_reduce_bn_scale , act_type='relu')
inception_5a_3x3 = mx.symbol.Convolution(name='inception_5a_3x3', data=inception_5a_relu_3x3_reduce , num_filter=320, pad=(1, 1), kernel=(3,3), stride=(1,1), no_bias=True)
inception_5a_3x3_bn = mx.symbol.BatchNorm(name='inception_5a_3x3_bn', data=inception_5a_3x3 , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_5a_3x3_bn_scale = inception_5a_3x3_bn
inception_5a_relu_3x3 = mx.symbol.Activation(name='inception_5a_relu_3x3', data=inception_5a_3x3_bn_scale , act_type='relu')
inception_5a_double3x3_reduce = mx.symbol.Convolution(name='inception_5a_double3x3_reduce', data=inception_4e_scale , num_filter=160, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=True)
inception_5a_double3x3_reduce_bn = mx.symbol.BatchNorm(name='inception_5a_double3x3_reduce_bn', data=inception_5a_double3x3_reduce , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_5a_double3x3_reduce_bn_scale = inception_5a_double3x3_reduce_bn
inception_5a_relu_double3x3_reduce = mx.symbol.Activation(name='inception_5a_relu_double3x3_reduce', data=inception_5a_double3x3_reduce_bn_scale , act_type='relu')
inception_5a_double3x3a = mx.symbol.Convolution(name='inception_5a_double3x3a', data=inception_5a_relu_double3x3_reduce , num_filter=224, pad=(1, 1), kernel=(3,3), stride=(1,1), no_bias=True)
inception_5a_double3x3a_bn = mx.symbol.BatchNorm(name='inception_5a_double3x3a_bn', data=inception_5a_double3x3a , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_5a_double3x3a_bn_scale = inception_5a_double3x3a_bn
inception_5a_relu_double3x3a = mx.symbol.Activation(name='inception_5a_relu_double3x3a', data=inception_5a_double3x3a_bn_scale , act_type='relu')
inception_5a_double3x3b = mx.symbol.Convolution(name='inception_5a_double3x3b', data=inception_5a_relu_double3x3a , num_filter=224, pad=(1, 1), kernel=(3,3), stride=(1,1), no_bias=True)
inception_5a_double3x3b_bn = mx.symbol.BatchNorm(name='inception_5a_double3x3b_bn', data=inception_5a_double3x3b , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_5a_double3x3b_bn_scale = inception_5a_double3x3b_bn
inception_5a_relu_double3x3b = mx.symbol.Activation(name='inception_5a_relu_double3x3b', data=inception_5a_double3x3b_bn_scale , act_type='relu')
inception_5a_pool = mx.symbol.Pooling(name='inception_5a_pool', data=inception_4e_scale , pooling_convention='full', pad=(1,1), kernel=(3,3), stride=(1,1), pool_type='avg')
inception_5a_pool_proj = mx.symbol.Convolution(name='inception_5a_pool_proj', data=inception_5a_pool , num_filter=128, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=True)
inception_5a_pool_proj_bn = mx.symbol.BatchNorm(name='inception_5a_pool_proj_bn', data=inception_5a_pool_proj , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_5a_pool_proj_bn_scale = inception_5a_pool_proj_bn
inception_5a_relu_pool_proj = mx.symbol.Activation(name='inception_5a_relu_pool_proj', data=inception_5a_pool_proj_bn_scale , act_type='relu')
inception_5a_concat = mx.symbol.Concat(name='inception_5a_concat', *[inception_5a_relu_1x1,inception_5a_relu_3x3,inception_5a_relu_double3x3b,inception_5a_relu_pool_proj] )
inception_5a_global_pool = mx.symbol.Pooling(name='inception_5a_global_pool', data=inception_5a_concat , pooling_convention='full', global_pool=True, kernel=(1,1), pool_type='avg')
inception_5a_1x1_down = mx.symbol.Convolution(name='inception_5a_1x1_down', data=inception_5a_global_pool , num_filter=64, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=False)
inception_5a_1x1_down_relu = mx.symbol.Activation(name='inception_5a_1x1_down_relu', data=inception_5a_1x1_down , act_type='relu')
inception_5a_1x1_up = mx.symbol.Convolution(name='inception_5a_1x1_up', data=inception_5a_1x1_down_relu , num_filter=1024, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=False)
inception_5a_prob = mx.symbol.Activation(name='inception_5a_prob', data=inception_5a_1x1_up , act_type='sigmoid')
inception_5a_prob_reshape = mx.symbol.Reshape(name='inception_5a_prob_reshape', data=inception_5a_prob , shape=(0,0, -2))
inception_5a_scale = mx.sym.broadcast_mul(inception_5a_concat, inception_5a_prob_reshape)
inception_5b_1x1 = mx.symbol.Convolution(name='inception_5b_1x1', data=inception_5a_scale , num_filter=352, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=True)
inception_5b_1x1_bn = mx.symbol.BatchNorm(name='inception_5b_1x1_bn', data=inception_5b_1x1 , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_5b_1x1_bn_scale = inception_5b_1x1_bn
inception_5b_relu_1x1 = mx.symbol.Activation(name='inception_5b_relu_1x1', data=inception_5b_1x1_bn_scale , act_type='relu')
inception_5b_3x3_reduce = mx.symbol.Convolution(name='inception_5b_3x3_reduce', data=inception_5a_scale , num_filter=192, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=True)
inception_5b_3x3_reduce_bn = mx.symbol.BatchNorm(name='inception_5b_3x3_reduce_bn', data=inception_5b_3x3_reduce , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_5b_3x3_reduce_bn_scale = inception_5b_3x3_reduce_bn
inception_5b_relu_3x3_reduce = mx.symbol.Activation(name='inception_5b_relu_3x3_reduce', data=inception_5b_3x3_reduce_bn_scale , act_type='relu')
inception_5b_3x3 = mx.symbol.Convolution(name='inception_5b_3x3', data=inception_5b_relu_3x3_reduce , num_filter=320, pad=(1, 1), kernel=(3,3), stride=(1,1), no_bias=True)
inception_5b_3x3_bn = mx.symbol.BatchNorm(name='inception_5b_3x3_bn', data=inception_5b_3x3 , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_5b_3x3_bn_scale = inception_5b_3x3_bn
inception_5b_relu_3x3 = mx.symbol.Activation(name='inception_5b_relu_3x3', data=inception_5b_3x3_bn_scale , act_type='relu')
inception_5b_double3x3_reduce = mx.symbol.Convolution(name='inception_5b_double3x3_reduce', data=inception_5a_scale , num_filter=192, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=True)
inception_5b_double3x3_reduce_bn = mx.symbol.BatchNorm(name='inception_5b_double3x3_reduce_bn', data=inception_5b_double3x3_reduce , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_5b_double3x3_reduce_bn_scale = inception_5b_double3x3_reduce_bn
inception_5b_relu_double3x3_reduce = mx.symbol.Activation(name='inception_5b_relu_double3x3_reduce', data=inception_5b_double3x3_reduce_bn_scale , act_type='relu')
inception_5b_double3x3a = mx.symbol.Convolution(name='inception_5b_double3x3a', data=inception_5b_relu_double3x3_reduce , num_filter=224, pad=(1, 1), kernel=(3,3), stride=(1,1), no_bias=True)
inception_5b_double3x3a_bn = mx.symbol.BatchNorm(name='inception_5b_double3x3a_bn', data=inception_5b_double3x3a , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_5b_double3x3a_bn_scale = inception_5b_double3x3a_bn
inception_5b_relu_double3x3a = mx.symbol.Activation(name='inception_5b_relu_double3x3a', data=inception_5b_double3x3a_bn_scale , act_type='relu')
inception_5b_double3x3b = mx.symbol.Convolution(name='inception_5b_double3x3b', data=inception_5b_relu_double3x3a , num_filter=224, pad=(1, 1), kernel=(3,3), stride=(1,1), no_bias=True)
inception_5b_double3x3b_bn = mx.symbol.BatchNorm(name='inception_5b_double3x3b_bn', data=inception_5b_double3x3b , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_5b_double3x3b_bn_scale = inception_5b_double3x3b_bn
inception_5b_relu_double3x3b = mx.symbol.Activation(name='inception_5b_relu_double3x3b', data=inception_5b_double3x3b_bn_scale , act_type='relu')
inception_5b_pool = mx.symbol.Pooling(name='inception_5b_pool', data=inception_5a_scale , pooling_convention='full', pad=(1,1), kernel=(3,3), stride=(1,1), pool_type='max')
inception_5b_pool_proj = mx.symbol.Convolution(name='inception_5b_pool_proj', data=inception_5b_pool , num_filter=128, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=True)
inception_5b_pool_proj_bn = mx.symbol.BatchNorm(name='inception_5b_pool_proj_bn', data=inception_5b_pool_proj , use_global_stats=True, fix_gamma=False, eps=0.000100)
inception_5b_pool_proj_bn_scale = inception_5b_pool_proj_bn
inception_5b_relu_pool_proj = mx.symbol.Activation(name='inception_5b_relu_pool_proj', data=inception_5b_pool_proj_bn_scale , act_type='relu')
inception_5b_concat = mx.symbol.Concat(name='inception_5b_concat', *[inception_5b_relu_1x1,inception_5b_relu_3x3,inception_5b_relu_double3x3b,inception_5b_relu_pool_proj] )
inception_5b_global_pool = mx.symbol.Pooling(name='inception_5b_global_pool', data=inception_5b_concat , pooling_convention='full', global_pool=True, kernel=(1,1), pool_type='avg')
inception_5b_1x1_down = mx.symbol.Convolution(name='inception_5b_1x1_down', data=inception_5b_global_pool , num_filter=64, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=False)
inception_5b_1x1_down_relu = mx.symbol.Activation(name='inception_5b_1x1_down_relu', data=inception_5b_1x1_down , act_type='relu')
inception_5b_1x1_up = mx.symbol.Convolution(name='inception_5b_1x1_up', data=inception_5b_1x1_down_relu , num_filter=1024, pad=(0, 0), kernel=(1,1), stride=(1,1), no_bias=False)
inception_5b_prob = mx.symbol.Activation(name='inception_5b_prob', data=inception_5b_1x1_up , act_type='sigmoid')
inception_5b_prob_reshape = mx.symbol.Reshape(name='inception_5b_prob_reshape', data=inception_5b_prob , shape=(0,0, -2))
inception_5b_scale = mx.sym.broadcast_mul(inception_5b_concat, inception_5b_prob_reshape)
pool5_7x7_s1 = mx.symbol.Pooling(name='pool5_7x7_s1', data=inception_5b_scale , pooling_convention='full', pad=(0,0), kernel=(7,7), stride=(1,1), pool_type='avg')
flatten_0=mx.symbol.Flatten(name='flatten_0', data=pool5_7x7_s1)
classifier = mx.symbol.FullyConnected(name='classifier', data=flatten_0 , num_hidden=1000, no_bias=False)
prob = mx.symbol.SoftmaxOutput(name='prob', data=classifier )
